CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY, 
    id_uuid UUID DEFAULT uuid_generate_v4(), 
    login VARCHAR(30) UNIQUE NOT NULL, 
    email VARCHAR(50) UNIQUE NOT NULL, 
    password VARCHAR(250) NOT NULL, 
    is_public BOOLEAN NOT NULL, 
    phone VARCHAR(20) UNIQUE NOT NULL, 
    image TEXT, 
    token_number INTEGER DEFAULT 1, 
    update_token INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY, 
    id_uuid UUID DEFAULT uuid_generate_v4(), 
    content VARCHAR(1000) NOT NULL, 
    author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tags (
    id SERIAL PRIMARY KEY, 
    id_post INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    tag VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS media (
    id SERIAL PRIMARY KEY, 
    id_post INTEGER REFERENCES posts(id) ON DELETE CASCADE, 
    img VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
    id SERIAL PRIMARY KEY,
    id_user INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    id_friend INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id_user, id_friend)
);

CREATE TABLE IF NOT EXISTS likes (
    id SERIAL PRIMARY KEY,
    id_post INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL,
    UNIQUE(id_post, author_id)
);

CREATE INDEX IF NOT EXISTS idx_posts_created_at_id ON posts(created_at DESC, id DESC);